### ISSUE TITLE
It seems that nexcloud does not check for sufficient free space

### ISSUE THREAD

**Issue by colapsid** [nextcloud/updater#586] opened 2024-10-24 06:29 UTC
Nextcloud Hub 9 (30.0.1)
It seems that nexcloud does not check for sufficient free space before updating. In my case, the 'data' folder is located on a separate mount point. At the time of testing, the disk size was 1 Gb.

### Expected behaviour
Check free disk space.

### Actual behaviour
The availability of free disk space is not checked and the update process gets stuck.

### Server configuration

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8.2

**Nextcloud version:** Nextcloud Hub 9 (30.0.1)

### Browser

**Browser name:** Chrome

**Browser version:** 125

**Operating system:** Ubuntu

**Comment by joshtrichards** [comment] 2024-10-24 14:36
Duplicate of #523

**Comment by joshtrichards** [comment] 2024-10-24 14:37
Out of curiosity, in what form did the update process get stuck? What were the immediate signs you saw?

**Closed by joshtrichards** 2024-10-24 14:36 UTC
Labels: bug, 0. Needs triage

**Comment by colapsid** [comment] 2024-10-25 13:09
Unfortunately, no. I reinstalled everything when nexcloud broke down after an unsuccessful update (Not enough free disk space).
