### ISSUE TITLE
 can't proceed past "Check for write permissions"

### ISSUE THREAD

**Issue by ITwrx** [nextcloud/updater#24] opened 2016-07-07 20:45 UTC
I can't proceed past "Check for write permissions" using the new updater. 

ownCloud 9.0.0 (stable)
Archlinux
php 7.0.5-1 (held back due to sessions not working with newer php versions and ownCloud 9.0)
nginx 1.10.1-1
mariadb 10.1.14-1

various perms tried but currently http:http dirs: 750 files: 640. i'm assuming script is running as http user? php(non cli) and nginx are both run as http user.

tried commenting out exception on line 335 and/or dumping $notWritablePaths[] on line 331 to see what paths weren't writable but both were "ignored". so, evidently i'm missing something. 

Thanks.

**Comment by MorrisJobke** [comment] 2016-07-08 08:08
> I can't proceed past "Check for write permissions" using the new updater.

Is there any output in the web page? What is the HTTP response (see in the web developer tools in the "Network" tab). There should be requests ending on "step" which are the actual steps. Could you check them and post their responses?

**Comment by ITwrx** [comment] 2016-07-08 14:33
> Is there any output in the web page?
only the red exclamation point stop sign icon and red highlighted "Check for write permissions"

> What is the HTTP response...
200:get, 200:get, 200:post, 500:post. all show /updater/ as the file.
i also got the following:
```
TypeError: response.response.forEach is not a function
performStepCallbacks[2]()
 %20line%20276%20%3E%20eval:109
performStep/httpRequest.onreadystatechange()
 %20line%20276%20%3E%20eval:71
 %20line%20276%20%3E%20eval:109:6
```

**Comment by MorrisJobke** [comment] 2017-08-08 19:53
Could not reproduce and seems to be a setup issue. If there are easy steps to reproduce this we are happy to work on this. Until then I will close this ticket.

**Closed by MorrisJobke** 2017-08-08 19:53 UTC
Labels: needs info

**Comment by ITwrx** [comment] 2017-08-08 20:12
i worked around it at the time somehow(probably just used the cli updater) and the newer versions of the updater work. 

thanks
