### ISSUE TITLE
tempdirectory (and maybe more in config.php defined folders) should be excluded from the check of extra files

### ISSUE THREAD

**Issue by eisenherzz** [nextcloud/updater#227] opened 2019-04-05 18:53 UTC
**Is your feature request related to a problem? Please describe.**
When updating Nextcloud:
Check for expected files
The following extra files have been found:
tmp
This folder is defined via `'tempdirectory' => '/www/htdocs/cloud/tmp',`

**Describe the solution you'd like**
tempdirectory (and maybe more in config.php defined folders) should be excluded from the check of extra files

**Comment by joshtrichards** [comment] 2023-06-18 16:33
Duplicate of #113

**Closed** 2023-09-07 15:57 UTC
Labels: enhancement
