### ISSUE TITLE
Inconsistency between `occ update:check` and updater

### ISSUE THREAD

**Issue by simonspa** [nextcloud/updater#254] opened 2019-11-27 15:35 UTC
I am expecting the command line tools to work somehow in the same way, but they don't. While `occ upgrade:check` reports the latest patch version, the updater just jumps immediately to the latest.

Also, there is no way to control this

```
$ sudo -u www-data php occ upgrade:check
Nextcloud 16.0.6 is available. Get more information /* ... */
Update for files_rightclick to version 0.15.1 is available.
2 updates available
```

Cool, so we can simply update and end up at the right place (i.e. not jumping versions)? No!

```
$ sudo -u www-data updater/updater.phar
Nextcloud Updater - version: v16.0.0beta3-4-gc7a4074

Current version is 16.0.0.

Update to Nextcloud 17.0.1 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-17.0.1.zip
```

Is there any plan to solve this?

Would you accept patches which allow specifying a version on the command line?

**Comment by nkakouros** [comment] 2020-06-06 09:59
Is there any feedback on this?

**Comment by joshtrichards** [comment] 2024-04-22 15:21
Duplicate of #122

**Closed** 2024-04-22 15:21 UTC
Labels: technical debt, feature: check for update, feature: upgrade
