### ISSUE TITLE
Updater app doesn’t need a navigation on the left

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/updater#43] opened 2016-10-04 14:39 UTC
There is only one entry on the left … the navigation is useless. ;)

We can just remove it, right? @MorrisJobke

**Comment by MorrisJobke** [comment] 2016-10-04 15:16
> We can just remove it, right?

Yes. I will do so

**Comment by jancborchardt** [comment] 2016-10-11 13:39
@MorrisJobke thanks!

**Comment by crumbking** [comment] 2016-12-11 10:32
+1   #2609

**Comment by crumbking** [comment] 2016-12-11 10:34
same here: Updater UI on phone only half visible. Lot of whitespace

**Comment by jancborchardt** [comment] 2016-12-16 02:42
@crumbking that’s a different issue, please open it separately :)

**Comment by MorrisJobke** [comment] 2017-08-31 11:52
Duplicate of #136

**Closed by MorrisJobke** 2017-08-31 11:52 UTC
Labels: design, enhancement
