### ISSUE TITLE
Updater doesn't do anything / All  checkmarks already set (or green)

### ISSUE THREAD

**Issue by Rilgamon** [nextcloud/updater#378] opened 2021-07-03 14:12 UTC
When using web-updater or commandline-updater a new update (21.0.3) is found. But the process ends with "Nextcloud is already latest version" and stays at current 21.0.2.

**System:** 
```
www-data@home:~/home/updater$ uname -a
Linux home 5.10.0-0.bpo.5-amd64 nextcloud/server#1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) x86_64 GNU/Linux
``` 

```
www-data@home:~/home/updater$ php -v
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
``` 

**Updater-Output**
www-data@home:~/home/updater$ php updater.phar 
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 21.0.2.

Update to Nextcloud 21.0.3 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-21.0.3.zip
Open changelog ↗

Steps that will be executed:
[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Continue update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] 
Nextcloud is already latest version

Keep maintenance mode active? [y/N] 
Maintenance mode already disabled

Maintenance mode is disabled

```
www-data@home:~/home$ php occ status
  - installed: true
  - version: 21.0.2.1
  - versionstring: 21.0.2
  - edition: 
```

**Comment by Rilgamon** [comment] 2021-07-04 08:54
Now that its moved here it seems the same problem mentioned here:
https://github.com/nextcloud/updater/issues/379

**Comment by igor-cali** [comment] 2021-07-09 15:08
@Rilgamon The update button on the web client worked for me today. I was able to successfully update.

**Comment by Brianetta** [comment] 2021-07-09 18:29
The update button on mine just does nothing. No feedback, no errors, nothing.

**Comment by blizzard4591** [comment] 2021-08-15 14:48
Same issue here.
```
$ php occ status
  - installed: true
  - version: 21.0.2.1
  - versionstring: 21.0.2
  - edition:
```
The settings first show 
![image](https://user-images.githubusercontent.com/130480/129482354-194afd5c-2770-4899-ac0f-ae2a0544d734.png)
and on clicking "Open Updater" immediately shows 
![image](https://user-images.githubusercontent.com/130480/129482373-b695beb8-bcea-443d-b5d2-44a3763f7936.png).

I tried running the updater by hand:
```
$ php --version
PHP 7.3.29-1~deb10u1 (cli) (built: Jul  2 2021 04:04:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.29-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
$ php updater/updater.phar
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 21.0.2.

Update to Nextcloud 21.0.4 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-21.0.4.zip
Open changelog ↗

Steps that will be executed:
[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Continue update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] Y
Nextcloud is already latest version

Keep maintenance mode active? [y/N] N
Maintenance mode already disabled

Maintenance mode is disabled
```
Any ideas? What can I do to help?

**Comment by igor-cali** [comment] 2021-08-20 09:19
> Same issue here.
> I tried running the updater by hand:
> 
> $ php updater/updater.phar
> Any ideas? What can I do to help?

I had similar issue from `v 21.0.3` to `v 21.0.4`.
I also had to manually run: `php updater/updater.phar`

**Comment by blizzard4591** [comment] 2021-08-20 09:33
> 
> 
> > Same issue here.
> > I tried running the updater by hand:
> > $ php updater/updater.phar
> > Any ideas? What can I do to help?
> 
> I had similar issue from `v 21.0.3` to `v 21.0.4`.
> I also had to manually run: `php updater/updater.phar`

Did it actually _work_ for you?
Because, for me, running the updater by hand **DID NOT UPDATE NEXTCLOUD**!
The version stays the same, even after the updater says `Update of code successful.` and `Nextcloud is already latest version`.

**Comment by igor-cali** [comment] 2021-08-20 09:38
> > > Same issue here.
> > > I tried running the updater by hand:
> > > $ php updater/updater.phar
> > > Any ideas? What can I do to help?
> > 
> > 
> > I had similar issue from `v 21.0.3` to `v 21.0.4`.
> > I also had to manually run: `php updater/updater.phar`
> 
> Did it actually _work_ for you?
> Because, for me, running the updater by hand **DID NOT UPDATE NEXTCLOUD**!
> The version stays the same, even after the updater says `Update of code successful.` and `Nextcloud is already latest version`.

It shows version 21.0.0 in the `settings/overview` web page of my instance.

**Comment by blizzard4591** [comment] 2021-08-20 09:45
For me, using the updater is an invariant action:
```
 $ php updater/updater.phar
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 21.0.2.

Update to Nextcloud 21.0.4 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-21.0.4.zip
Open changelog ↗

Steps that will be executed:
[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Continue update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] y
Nextcloud is already latest version

Keep maintenance mode active? [y/N] N
Maintenance mode already disabled

Maintenance mode is disabled
$ php updater/updater.phar
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 21.0.2.

Update to Nextcloud 21.0.4 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-21.0.4.zip
Open changelog ↗

Steps that will be executed:
[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Continue update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] y
Nextcloud is already latest version

Keep maintenance mode active? [y/N] n
Maintenance mode already disabled

Maintenance mode is disabled
$
```
So, executing the updater a second (or however many times) directly in sequence produces the same output everytime, but no change.

**Comment by Benouare** [comment] 2021-08-31 08:28
@blizzard4591 , did u succeed to go to 22 ? In my case not yet.

**Comment by dirks** [comment] 2021-10-05 08:54
> @blizzard4591 , did u succeed to go to 22 ? In my case not yet. I am was stuck as u @21.0.X and now i am on 21.0.4, but i cant go to 22...

Don't know if this is still relevant to you @Benouare , but I could upgrade from 21.0.5.1 to 22.2.0.2 with the following steps

1. remove the update-xyz folder in the nextcloud data folder
2. start the pre-update procedure via web interface (`Open updater` button)
3. running `occ upgrade`

**Comment by Benouare** [comment] 2021-10-05 09:58
> > @blizzard4591 , did u succeed to go to 22 ? In my case not yet. I am was stuck as u @21.0.X and now i am on 21.0.4, but i cant go to 22...
> 
> Don't know if this is still relevant to you @Benouare , but I could upgrade from 21.0.5.1 to 22.2.0.2 with the following steps
> 
> 1. remove the update-xyz folder in the nextcloud data folder
> 2. start the pre-update procedure via web interface (`Open updater` button)
> 3. running `occ upgrade`

Hi,
Thx for the update! 
I have just run the updater.phar ... It looks like it's the target is the 21.0.5 ! So it may goes to the 22.x after! Thx again for the news ! 
Cheers
Benoît

**Comment by dirks** [comment] 2021-10-05 10:10
> Hi, Thx for the update! I have just run the updater.phar ... It looks like it's the target is the 21.0.5 ! So it may goes to the 22.x after! Thx again for the news ! Cheers Benoît

Maybe, but be aware that the updates are usually rolled out gradually to the userbase, the schedule for 22.1.1 is given at
https://nextcloud.com/blog/fresh-updates-here-22-2-0-21-0-5-and-20-0-13/

> Nextcloud 22.1.1 was made available to about a third of our userbase already. Our plan is:
>
>    go to 70% on 7th October
>    go to 100% on 14th October

If you want to upgrade earlier you can always download the archive and [upgrade manually](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html).

**Comment by elhananjair** [comment] 2021-10-22 04:46
> > @blizzard4591 , did u succeed to go to 22 ? In my case not yet. I am was stuck as u @21.0.X and now i am on 21.0.4, but i cant go to 22...
> 
> Don't know if this is still relevant to you @Benouare , but I could upgrade from 21.0.5.1 to 22.2.0.2 with the following steps
> 
>     1. remove the update-xyz folder in the nextcloud data folder
> 
>     2. start the pre-update procedure via web interface (`Open updater` button)
> 
>     3. running `occ upgrade`

I have removed that folder now its upgrading, thanks @dirks

**Comment by joshtrichards** [comment] 2023-11-30 23:01
It sounds like the `.step` folder may not be getting cleaned up for some of you after each update/upgrade cycle for some reason.

You can remove  them manually (as noted above in some of the comments), but the safest is to run `occ maintenance:repair` which should accomplish the same thing (along with some other things that shouldn't hurt).

Of course always have backups before doing updates/upgrades.

To get to the bottom of what's going on, it would be helpful to see your `data/updater.log` file after the next successful Updater run followed the next unsuccessful one.

**Comment by joshtrichards** [comment] 2024-10-16 20:20
Closing since this issue hasn't had new traffic or info on it needed to determine root cause. 

If you encounter this situation, please check your `updater.log` to determine what happened with the *prior* update that prevented the final step from clearing out the `.step` file. Then create a dedicated Issue with the details about your environment/etc.

**Closed by joshtrichards** 2024-10-16 20:20 UTC
Labels: bug, needs info, feature: finalize, hotspot: .step management
