### ISSUE TITLE
(un)expected files

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/updater#68] opened 2016-12-12 09:31 UTC
all-inkl.com provides installing Nextcloud through their web interface. They add `$CONFIG['tempdirectory'] = '/www/htdocs/user/cloud/tmp/';` to `config.php` and create that directory.

While the update from 10.0.1 to 10.0.2 the updater condemned this directory `/tmp` as _expected files_ and stopped there. So I commented out the config line and deleted the directory, and then the updater ran the update as expected. Questions arise:

* shouldn't this be named _*un*expected files_?
* wouldn't the `tempdirectory` configuration item make the directory yet _expected_ and therefore not a show stopper?

**Comment by MorrisJobke** [comment] 2016-12-14 21:10
@mcnesium Thanks for the feedback. Let me try to reproduce this and look into this.

**Comment by mcnesium** [comment] 2017-01-20 16:41
Still doing it in NC 11:

![bildschirmfoto 2017-01-20 um 17 40 01](https://cloud.githubusercontent.com/assets/476060/22157331/947c15ee-df37-11e6-950b-0d7d393f87e3.png)


What about something like this:

    $CONFIG['expected_files'] = array( "logs", "tmp" );

**Comment by MorrisJobke** [comment] 2017-01-21 01:25
I would rather go for following: Instead of failing hard showing those files to the user and allow the user to approve those files as being okay (on their own risk). This would also fix the issues in #23 for example.

**Comment by elsobrino** [comment] 2017-01-24 07:18
I am currently stumbling on this issue, too, while updating from 9.0.53 to 10.0.3 with two other paths:

![bildschirmfoto 2017-01-24 um 07 58 16](https://cloud.githubusercontent.com/assets/450369/22237520/a6a0bb1c-e20c-11e6-9aa3-5d37d500665e.png)

`lost+found` seems a bigger issue, because after adding it to `getExpectedElementsList()`, the next step 'Check for write permissions' fails.

![bildschirmfoto 2017-01-24 um 08 17 38](https://cloud.githubusercontent.com/assets/450369/22237673/9c124d9a-e20d-11e6-8777-439b4e0bc54c.png)

**Comment by fireba11** [comment] 2017-03-11 13:27
Basically every shared host environment will have the odd extra files in there. For example in an ISPconfig web there is a stats and an error folder. You need to be able to either ignore these extra files, confirm them (as in it gets remembered) or have a config option to tell nextcloud what additional things are expected.

**Comment by McLibboc** [comment] 2017-03-19 09:23
Same problem here when trying to update from 11.01 to 11.02.

Any workaround until this is "enhanced"?

**Comment by benkeks** [comment] 2017-03-28 13:33
@McLibboc Moving the extra files to some directory outside the nextcloud installation, performing the update, and moving the files back worked for me.

**Comment by stratege1401** [comment] 2018-03-17 01:19
8831 was closed because old duplicate (  12 dec 2016 - 17 march 2018 !!   ), but what is planned ?

**Comment by ygoe** [comment] 2018-05-04 13:15
I have "fixed" th updater as suggested in my duplicate issue by adding the extra directory into the list. Now it's completely broken and gone. I guess automatic updating isn't possible with Nextcloud. I now have to save the remains, repair the hosting environment and reinstall it newly. On a production system. Nice Friday afternoon.

![nextcloudupdatererror](https://user-images.githubusercontent.com/868315/39629880-dce6811a-4fad-11e8-895e-76af37efd8ed.png)

**Comment by jospoortvliet** [comment] 2018-05-04 13:28
So perhaps the safest 'fix' is to tell people to do what was suggested by @benkeks - https://github.com/nextcloud/updater/issues/68#issuecomment-289770868
move the files out of the way, perform the upgrade, move them back.

**Comment by stratege1401** [comment] 2018-05-04 14:40
sometimes, "moving files around" is a no go !!! breaking symlinks for exemple as sometimes you dont keept track of them ...

this issue is like a dog running at is own tail:  
#8831 #8952 #163 #3045 #6906 ....... some of them are closed, referring to another closed referring to another closed referring to the first again and so on ...

maybe this check for extra files should simply go away ...

**Comment by ygoe** [comment] 2018-05-04 15:26
@jospoortvliet I can tell you what happens when I move the php-fcgi file "out of the way": The web page will not execute and the upgrade cannot take place. This file is an essential part of the hosting environment. And because people tend to delete it, and then the web server fails to restart, the files are marked immutable in the file system. So at least the updater wasn't able to kick itself out of the world. But it also failed to handle this situation and left me alone with an unusable and undefined state.

If the check for extra files can determine what files don't belong to Nextcloud, then these files should not be complained about, but rather excluded from deleting. That's what would help a lot.

**Comment by benkeks** [comment] 2018-05-04 18:30
Yeah, my suggestion was really only meant as a workaround for certain situations.

I actually also think that it's an awkward design decision to allow users to install NextCloud instances in folders with extra files, but then prevent them from upgrading such installations. The upgrade procedure is stricter than the setup, where it should rather be the other way around (or at least equal in strictness).

**Comment by CapSel** [comment] 2020-10-08 21:07
Problem still exists for me.

**Comment by JackRoublard** [comment] 2023-02-25 13:28
Bumping the issue ; IMO installations that do not have the luxury of having Nextcloud installed in a perfectly empty directory are way too common for this to be ignored; even moreso since the code signing feature has been added.

**Comment by brainchild0** [comment] 2023-07-26 20:22
Some hosting environments, especially shared hosting environments, offer no means for preventing the assertion of certain extra directory items in an application directory.

In a Plesk hosting environment, several items have been observed as added to the root level of the application directory, including `.php-ini`, `.php-version`, and `.well-known`. 

I suggest adding support for a site-configurable list of file names that should be ignored by the updater when checking the integrity of the application directory. For usability, the standard installation may populate it with initial items that are commonly found in certain environments.

The feature might be implemented either through a new configuration field, or through a separate file following the design pattern applied in `.gitignore`.

**Comment by kesselb** [comment] 2023-07-27 10:52
This sounds like a great feature, but currently there are no plans to implement it. Therefore, I will close this ticket for now. This does not mean we don't want this feature, but it is not on our list of things to do soon.

**Closed by kesselb** 2023-07-27 10:52 UTC
Labels: enhancement

**Comment by Alseenrodelap** [comment] 2024-01-23 09:04
Still this issue exists.
It's a safety feature that enables a installation in a folder, but prohibits any updates. How is that safe in the long run?
No good thinking here.
