### ISSUE TITLE
Replace entry points Can't replace entry point: index.php

### ISSUE THREAD

**Issue by Ang3er** [nextcloud/updater#199] opened 2018-12-01 15:10 UTC
Error while doing the update, ends with
Replace entry points
Can't replace entry point: index.php

The permissioncheck did not check dat?

Tanks in advance
Dominik

**Comment by MorrisJobke** [comment] 2018-12-03 14:57
> The permissioncheck did not check dat?

Usually it should. Could you check the updater.log in the data directory? Maybe this holds more info.

**Comment by mtimyself** [comment] 2019-04-07 17:29
I am having the same issue when trying to update from version 14 to version 15.
https://pastebin.com/q9RH7A4F

**Comment by joshtrichards** [comment] 2024-04-21 18:48
This failure is a very simple `file_put_contents` call. And we do check write permissions earlier on.

https://github.com/nextcloud/updater/blob/1c564a63788f60f9e07e3e00aa7915e72ef21183/index.php#L827

Since there are only two reports in this issue (after five years) and we're unable to reproduce I may close this issue out soon - but wanted to ask two more questions in case it turns something up:

1. What OS and filesystem is/was this?

2. Also, is/was there a thing unusual about your data versus your installation folder? Like perhaps is the data directory reference in your installation folder a symbolic link to somewhere else on your filesystems?

**Closed** 2024-04-23 18:02 UTC
Labels: bug, needs info, feature: entry points
