### ISSUE TITLE
Could not unlink during update

### ISSUE THREAD

**Issue by JH6** [nextcloud/updater#225] opened 2019-06-10 18:21 UTC
I tried to update Nextcloud from 16.0.0 to 16.0.1 using the updater. On the step "deleting old files" it failed with a message "cloud not unlink /var/www/html/updater/../robots.txt" If I renamed robots.txt for testing purposes it gave the same could not unlink error but for the .htaccess file.
After changing the owner of the /var/www/html folder to www-data:www-data the issue is resolved. Seems the same as: https://github.com/nextcloud/updater/issues/139
Maybe something to write in the installation manual (or I might have overlooked) or make sure it is checked somewhere in the update process.

**Comment by MorrisJobke** [comment] 2019-07-03 15:10
We should check the permissions of the Nextcloud root folder as well: #66 


Let's close it as duplicate of #66

**Closed by MorrisJobke** 2019-07-03 15:10 UTC
