### ISSUE TITLE
Updater does not start NC13.0.0

### ISSUE THREAD

**Issue by rollanders** [nextcloud/updater#161] opened 2018-04-26 13:05 UTC
### Steps to reproduce
1. Open Nextcloud /index.php/settings/admin
2. Press button Open updater
3. 

### Expected behaviour
Updater should start

### Actual behaviour
get a message Could not start updater. Please try manual update. 

I do not want to risk a crash doung manual update. 

## Server configuration detail
**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64
**Webserver:** nginx/1.13.8 (fpm-fcgi)
**Database:** mysql 10.2.13
**PHP version:** 7.1.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, intl, ldap, mcrypt, memcached, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, redis, zip, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Fresh install
**Where did you install Nextcloud from:** unknown
Used these instructions for installing https://www.linuxbabe.com/docker/onlyoffice-nextcloud-integration-docker

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - apporder: 0.4.1
 - audioplayer: 2.2.5
 - calendar: 1.6.1
 - caniupdate: 0.1.2
 - cms_pico: 0.9.7
 - contacts: 2.1.3
 - dav: 1.4.6
 - external: 3.0.2
 - federatedfilesharing: 1.3.1
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - oauth2: 1.1.0
 - onlyoffice: 1.2.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - comments
 - encryption
 - federation
 - files_external
 - files_frommail
 - files_versions
 - files_videoplayer
 - nextcloud_announcements
 - notifications
 - ownpad
 - quota_warning
 - sharebymail
 - socialsharing_email
 - socialsharing_facebook
 - theming
 - user_external
 - user_ldap

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "173.249.5.125",
        "nginx-server",
        "cloud.korskyrkan-intra.se"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/173.249.5.125",
    "dbtype": "mysql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "onlyoffice": {
        "DocumentServerUrl": "\/ds-vpath\/",
        "DocumentServerInternalUrl": "http:\/\/onlyoffice-document-server\/",
        "StorageUrl": "http:\/\/nginx-server\/"
    },
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36

**Operating system:** 

## Logs
get these errors in the log

Error | no app in context | issuetemplate | 2018-04-26T15:04:17+0200
Error | PHP | Array to string conversion at /var/www/html/custom_apps/issuetemplate/lib/DetailManager.php#104

**Comment by MorrisJobke** [comment] 2018-04-26 13:19
Duplicate of #160

**Closed by MorrisJobke** 2018-04-26 13:19 UTC
