### ISSUE TITLE
Updater fails with extra files

### ISSUE THREAD

**Issue by ygoe** [nextcloud/updater#163] opened 2018-04-28 15:59 UTC
![nextcloud-updater](https://user-images.githubusercontent.com/868315/39398425-dc0eca76-4b0d-11e8-87b6-38dec5a94545.png)

The directory "cgi-bin" is part of the hosting infrastructure and cannot be removed without destroying the website. What next?

**Comment by ygoe** [comment] 2018-05-04 08:44
Where is the code I need to change to disable that particular check? I'd really like to keep my installation up-to-date but manually installing this every time isn't really great.

**Comment by MorrisJobke** [comment] 2018-05-04 09:52
Duplicate of #68

Code is at https://github.com/nextcloud/updater/blob/master/index.php#L293-L328

**Closed by MorrisJobke** 2018-05-04 09:52 UTC
