### ISSUE TITLE
Update to 12.0.2 failed: "Could not unlink /var/www/nextcloud/updater/../.htaccess"

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/updater#139] opened 2017-09-11 13:56 UTC
Just encountered the case where an instance couldn't be updated to 12.0.2 because apparently the `.htaccess` file couldn't be removed, but the "Check for write permissions" check executed nicely:

![error](https://user-images.githubusercontent.com/878997/30277911-7ceea07e-9709-11e7-815f-c48d38c5f2ed.png)

In the debugging session it turned out that `/var/www/nextcloud/` is owned by `root:root` but all files below are owned by `www-data:www-data`. Doing a `chown www-data:www-data /var/www/nextcloud` resolved the issue.

We should already catch this situation in the "Check for write permissions" step. Let me see if I can reproduce this somehow nicely.

**Comment by wiwie** [comment] 2018-01-29 10:13
this helped me. I had the same problem with update 12.0.4 -> 12.0.5 with regards to /var/www/nextcloud/cron.php

**Comment by hemanthsoni** [comment] 2019-05-02 22:31
Thanks! This worked for me too.

**Comment by MorrisJobke** [comment] 2019-07-03 15:10
We should check the permissions of the Nextcloud root folder as well: #66 


Let's close it as duplicate of #66

**Closed by MorrisJobke** 2019-07-03 15:10 UTC
Labels: bug
