### ISSUE TITLE
[NC 10/11] Improve the Updater App: currently it deinstalls apps but does not reload and restart them

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/updater#79] opened 2017-01-19 21:37 UTC
re-opened from https://github.com/nextcloud/server/issues/3172 here:

On my debian 8 servers running previously NC 10, now NC 11.0.1, I noticed that the updater works very well but

#### installed apps were stopped and not reloaded and not restarted when server software was updated.

The update app disabled i.a. Music Player, Contacts, Calendar, TOTP Provider, Disable Remember Login, but did not reinstall and reload these apps.

#### ad-hoc proposal: a check list of apps which requires manual re-installation and re-activation

At least a `check list` (of previously installed and enabled apps) should be available with which the NC Admin can re-install and enable these apps one by one.

The current way how the updater works is, in my view, unsatisfying in that respect.

**Comment by MariusBluem** [comment] 2017-01-19 21:53
What do you think? @MorrisJobke @LukasReschke 🤔 I think a checklist would be a bit oversized, as we already have the message after the upgrade, telling the user which apps were disabled - so that he knows which ones he need to re-enable or maybe update 😁 ... but the process might be overthought - true 😉🙈

**Comment by Wikinaut** [comment] 2017-01-19 22:15
Exactly this is, what I don't like: the output on the web page while upgrading. At least I expect a static page (in the Admin panel, or in the App window) which lists all previously-installed Apps which (may) require re-installation.

**Comment by MorrisJobke** [comment] 2017-01-19 22:26
This is already fixed in the server: https://github.com/nextcloud/server/issues/239 (will be released with 12) We don't disable apps anymore. ;) 

The limitation of PHP 7 is caused by the ability of PHP 7 being able to also catch syntax errors from within the code. In pre-7 it simply dies.

@MariusBluem Even if this sounds like a updater issue, it's actually the code that lives in the server(occ upgrade). The updater only replaces old code and then hands off to the occ upgrade/web UI migration process.

Sorry for this confusion - this was a server issue.

**Closed by MorrisJobke** 2017-01-19 22:26 UTC
Labels: 0. Needs triage, enhancement

**Comment by Wikinaut** [comment] 2017-01-19 23:01
@MorrisJobke :+1:
