### ISSUE TITLE
Stuck on check for writepermissions (11.0.0 -> 11.0.1 RC1)

### ISSUE THREAD

**Issue by JSoko** [nextcloud/updater#75] opened 2017-01-12 06:37 UTC
While upgrading from 11.0.0 to 11.0.1 RC1 the Updater get stuck on Check for write permissions
(see https://github.com/nextcloud/updater/issues/66 )

Only /www/cloud/updater/../apps/ seems to be affacted
See also: https://github.com/nextcloud/updater/issues/66
doing

> sudo chown -R www-data:www-data /var/www/cloud
and restart the update fixes this issue
_IMHO at least it should be mentioned on the Error message that
sudo chown -R www-data:www-data /var/www/nextcloud
could solve the problem.._

**Comment by MorrisJobke** [comment] 2017-01-12 09:05
Duplicate of #66

**Closed by MorrisJobke** 2017-01-12 09:05 UTC

**Comment by JSoko** [comment] 2017-01-16 10:50
That issue also occured again while updating from 11.0.1RC1 to 11.0.1
