### ISSUE TITLE
Limit manual adjustments after update

### ISSUE THREAD

**Issue by MeCias** [nextcloud/updater#244] opened 2019-09-28 06:50 UTC
Hello,

I managed to remove all tweaks out of the .htaccess so that after the update I do not have to adjust the file every time NC was updated. 
The last file I have to tweak still after every update is the config.php, since my theme that I have (not the theme app) is getting switched off every time. The pain is that you have to connect via ftp to adjust it. It would be awesome, there could be a solution within NC. Something over the notification icon for instance, that tells me that the updater app switched off my theme if I like to switch it on again. Or something similar. 
Thanks in advance for considering.

**Comment by joshtrichards** [comment] 2024-04-22 21:52
Duplicate of nextcloud/server#2785

**Closed by joshtrichards** 2024-04-22 21:52 UTC
Labels: enhancement, needs info, feature: upgrade
