### ISSUE TITLE
Update to V23.0.0 knocks out all major apps

### ISSUE THREAD

**Issue by KvoiceOxford** [nextcloud/updater#400] opened 2021-12-03 18:03 UTC
![V23 0 0](https://user-images.githubusercontent.com/77303051/144650846-a46bc8ee-3dff-4c7f-8411-cd8d8bc060a9.jpg)

**Comment by EchedeyLR** [comment] 2021-12-11 13:46
@KvoiceOxford if you start the migration anywasy, do you get an error migrating the DB schema?

That is my current case so I am locked since the NC instance was upgraded.

**Comment by KvoiceOxford** [comment] 2021-12-11 14:27
@EchedeyLR Yes, exactly that. All that I did was to launch the updater and I've been locked out of NextCloud ever since. Sadly, this is the third time in 2021 that I've been locked out of NextCloud for at least a week immediately following an update. In 2022 I must review my use of NextCloud perhaps in favour of using the Ubuntu SNAP version which I know lags behind the latest release, but the SNAP does bring much greater stability and reliability which, in the end, in my view, trumps the latest available functionality. Reliability is king. I am a really great admirer of NextCloud, but we all need to work harder to ensure rock-solid stable releases over a rush to push out the latest untested developments. I am still on board, but I am not the only person making this same observation. A stable release should mean exactly what it says on the tin.

**Comment by EchedeyLR** [comment] 2021-12-30 16:00
Any update into this.

**Comment by joshtrichards** [comment] 2024-04-22 02:09
> Update to V23.0.0 knocks out all major apps

Is your subject referring to the lower part of your screenshot where it says the "These incompatible apps will be disabled"?

Later, in response to a comment, you mention db schema errors which is something else entirely from your screenshot.

Your initial report was a bit vague so it's unclear.

For the latter, Unfortunately I can only speculate since the exact error message seen wasn't mentioned nor any log entries provided. If this comes up in the future, all db migrations are sent to the main Nextcloud log).

Best guess is you experienced nextcloud/server#30226.

This also appears to be a duplicate of a report made at nextcloud/server#30098. So I'm closing this out here. 

Hopefully you long ago got this worked out via other channels.

**Closed by joshtrichards** 2024-04-22 02:09 UTC
Labels: bug, 0. Needs triage, feature: apps management
