### ISSUE TITLE
Add note to Updater about staged releases

### ISSUE THREAD

**Issue by TraceyC77** [nextcloud/updater#140] opened 2017-09-14 13:20 UTC
Given that a server administrator can see that NC 12 is the latest version provided by the "stable" channel, it can be confusing that the Updater UI (and via cli) show 11.0.4 as "up to date" for stable.

On my server, Nextcloud was installed manually with the "Web Installer" from these instructions just the other day:
https://nextcloud.com/install/#instructions-server
"Web Installer for shared hosts" tab

On that page, it does properly mention that it can take up to a month before a major version becomes available through the web installer and updater. It doesn't mention when the release of 12 was, so I have no idea what a month from 12's release was.

I recommend adding that verbiage to the Updater UI and cli output. This would prevent a server admin from wondering why the Updater considers an older version of NC as "up to date".

Ideally, the Updater would indicate the actual latest version of the software (in this case 12) and indicate that it is not yet available for this particular installation.

**Comment by joshtrichards** [comment] 2024-04-22 15:22
Related: #122

**Comment by joshtrichards** [comment] 2024-10-17 14:37
Duplicate of #382

**Closed by joshtrichards** 2024-10-17 14:37 UTC
Labels: enhancement, feature: check for update
