### ISSUE TITLE
Update from 17.0.2 to 18.0.0 throws errors on repair steps for talk app

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/updater#266] opened 2020-01-24 23:45 UTC
Don't know if this is anything to worry about, Talk App seems to work, though.

![nextcloud_18_update_errors](https://user-images.githubusercontent.com/29312856/73111320-3cc52f80-3f0a-11ea-8663-f5ebdcc90d1d.png)

System Info:
- PHP 7.3.11
- Nginx 1.16.1
- Mariadb 10.4.10

**Comment by kesselb** [comment] 2020-01-29 18:00
Closing as duplicate of https://github.com/nextcloud/server/issues/19102

**Closed by kesselb** 2020-01-29 18:00 UTC
