### ISSUE TITLE
Error updater - Delete old files

### ISSUE THREAD

**Issue by zoid009** [nextcloud/updater#249] opened 2019-11-06 12:42 UTC
I have a problem updating

Initializing
Current version is 15.0.1.
Update to Nextcloud 16.0.5 available. (channel: "stable")

Delete old files
Could not rmdir: /var/www/html/updater/../lib

```
LogFile - updater.log
...
2019-11-06T12:33:17+0000 6eCmcoixA8 [info] checkForUpdate() Array
(
    [version] => 16.0.5.1
    [versionstring] => Nextcloud 16.0.5
    [url] => https://download.nextcloud.com/server/releases/nextcloud-16.0.5.zip
    [web] => https://docs.nextcloud.com/server/16/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=16.0.5
    [autoupdater] => 1
    [eol] => 0
    [signature] => iAsxJoaWRQ/1A0M3PuiDehji4x0Ci158wpa5IAv+oZbuWdhOqZjcZbLf/2cWWeCL
ggZX8WJpdJw8ZDKNtInVpfcbI558mu0L9axjl7Cpl9T8lvF9uXOa26tgeuVV5Zh0
TKlB2rdZESjvMgCNgK7WgsYqCwspvnUsRRthssuSHA0mLCJuFDr73FiDi4fQPBlr
UuRojwQ1uHlNgct/cBElCwqCWkX4mx4CRC0jQh7jV/rdF4Cy0+ajWXMOBJgkyDkG
CLEAXZOCRmDQGFJT30TACL+cVYTrhMHGsha8I4v5/LOQhYQRaDLVqHPbrvJ2ge1N
ZGWQu68eon7Vfr0iKKPJ3A==
)

2019-11-06T12:33:17+0000 6eCmcoixA8 [info] end of checkForUpdate() Update to Nextcloud 16.0.5 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://download.nextcloud.com/server/releases/nextcloud-16.0.5.zip</code>
2019-11-06T12:33:29+0000 cBOK076gaU [info] request to updater
2019-11-06T12:33:29+0000 cBOK076gaU [info] currentStep()
2019-11-06T12:33:29+0000 cBOK076gaU [info] POST request for step "1"
2019-11-06T12:33:29+0000 cBOK076gaU [info] startStep("1")
2019-11-06T12:33:29+0000 cBOK076gaU [info] checkForExpectedFilesAndFolders()
2019-11-06T12:33:29+0000 cBOK076gaU [info] rollbackChanges("1")
2019-11-06T12:33:29+0000 cBOK076gaU [info] unlink .step
2019-11-06T12:33:29+0000 cBOK076gaU [info] end of  rollbackChanges()
2019-11-06T12:33:53+0000 OjnD0pKgIF [info] request to updater
2019-11-06T12:33:53+0000 OjnD0pKgIF [info] currentStep()
2019-11-06T12:33:53+0000 OjnD0pKgIF [info] POST request for step "1"
2019-11-06T12:33:53+0000 OjnD0pKgIF [info] startStep("1")
2019-11-06T12:33:53+0000 OjnD0pKgIF [info] checkForExpectedFilesAndFolders()
2019-11-06T12:33:53+0000 OjnD0pKgIF [info] end of checkForExpectedFilesAndFolders()
2019-11-06T12:33:53+0000 OjnD0pKgIF [info] endStep("1")
2019-11-06T12:33:53+0000 bsm8V4GjH9 [info] request to updater
2019-11-06T12:33:53+0000 bsm8V4GjH9 [info] currentStep()
2019-11-06T12:33:53+0000 bsm8V4GjH9 [info] Step 1 is in state "end".
2019-11-06T12:33:53+0000 bsm8V4GjH9 [info] POST request for step "2"
2019-11-06T12:33:53+0000 bsm8V4GjH9 [info] startStep("2")
2019-11-06T12:33:53+0000 bsm8V4GjH9 [info] checkWritePermissions()
2019-11-06T12:33:53+0000 bsm8V4GjH9 [info] end of checkWritePermissions()
2019-11-06T12:33:53+0000 bsm8V4GjH9 [info] endStep("2")
2019-11-06T12:33:54+0000 E5gtFiKgwX [info] request to updater
2019-11-06T12:33:54+0000 E5gtFiKgwX [info] currentStep()
2019-11-06T12:33:54+0000 E5gtFiKgwX [info] Step 2 is in state "end".
2019-11-06T12:33:54+0000 E5gtFiKgwX [info] POST request for step "3"
2019-11-06T12:33:54+0000 E5gtFiKgwX [info] startStep("3")
2019-11-06T12:33:54+0000 E5gtFiKgwX [info] createBackup()
2019-11-06T12:34:04+0000 E5gtFiKgwX [info] end of createBackup()
2019-11-06T12:34:04+0000 E5gtFiKgwX [info] endStep("3")
2019-11-06T12:34:04+0000 6XPoam1djX [info] request to updater
2019-11-06T12:34:04+0000 6XPoam1djX [info] currentStep()
2019-11-06T12:34:04+0000 6XPoam1djX [info] Step 3 is in state "end".
2019-11-06T12:34:04+0000 6XPoam1djX [info] POST request for step "4"
2019-11-06T12:34:04+0000 6XPoam1djX [info] startStep("4")
2019-11-06T12:34:04+0000 6XPoam1djX [info] downloadUpdate()
2019-11-06T12:34:04+0000 6XPoam1djX [info] getUpdateServerResponse()
2019-11-06T12:34:04+0000 6XPoam1djX [info] updaterServer: https://updates.nextcloud.org/updater_server/
2019-11-06T12:34:04+0000 6XPoam1djX [info] releaseChannel: stable
2019-11-06T12:34:04+0000 6XPoam1djX [info] internal version: 15.0.1.2
2019-11-06T12:34:04+0000 6XPoam1djX [info] updateURL: https://updates.nextcloud.org/updater_server/?version=15x0x1x2xxxstablexx2019-01-10T14%3A40%3A31%2B00%3A00+9325e42d3b48215b5b84397bb4a7694fecad3dbcx7x2x24
2019-11-06T12:34:05+0000 6XPoam1djX [info] getUpdateServerResponse response: Array
(
    [version] => 16.0.5.1
    [versionstring] => Nextcloud 16.0.5
    [url] => https://download.nextcloud.com/server/releases/nextcloud-16.0.5.zip
    [web] => https://docs.nextcloud.com/server/16/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=16.0.5
    [autoupdater] => 1
    [eol] => 0
    [signature] => iAsxJoaWRQ/1A0M3PuiDehji4x0Ci158wpa5IAv+oZbuWdhOqZjcZbLf/2cWWeCL
ggZX8WJpdJw8ZDKNtInVpfcbI558mu0L9axjl7Cpl9T8lvF9uXOa26tgeuVV5Zh0
TKlB2rdZESjvMgCNgK7WgsYqCwspvnUsRRthssuSHA0mLCJuFDr73FiDi4fQPBlr
UuRojwQ1uHlNgct/cBElCwqCWkX4mx4CRC0jQh7jV/rdF4Cy0+ajWXMOBJgkyDkG
CLEAXZOCRmDQGFJT30TACL+cVYTrhMHGsha8I4v5/LOQhYQRaDLVqHPbrvJ2ge1N
ZGWQu68eon7Vfr0iKKPJ3A==
)

2019-11-06T12:34:15+0000 6XPoam1djX [info] end of downloadUpdate()
2019-11-06T12:34:15+0000 6XPoam1djX [info] endStep("4")
2019-11-06T12:34:16+0000 NXluxiBisu [info] request to updater
2019-11-06T12:34:16+0000 NXluxiBisu [info] currentStep()
2019-11-06T12:34:16+0000 NXluxiBisu [info] Step 4 is in state "end".
2019-11-06T12:34:16+0000 NXluxiBisu [info] POST request for step "5"
2019-11-06T12:34:16+0000 NXluxiBisu [info] startStep("5")
2019-11-06T12:34:16+0000 NXluxiBisu [info] verifyIntegrity()
2019-11-06T12:34:16+0000 NXluxiBisu [info] getUpdateServerResponse()
2019-11-06T12:34:16+0000 NXluxiBisu [info] updaterServer: https://updates.nextcloud.org/updater_server/
2019-11-06T12:34:16+0000 NXluxiBisu [info] releaseChannel: stable
2019-11-06T12:34:16+0000 NXluxiBisu [info] internal version: 15.0.1.2
2019-11-06T12:34:16+0000 NXluxiBisu [info] updateURL: https://updates.nextcloud.org/updater_server/?version=15x0x1x2xxxstablexx2019-01-10T14%3A40%3A31%2B00%3A00+9325e42d3b48215b5b84397bb4a7694fecad3dbcx7x2x24
2019-11-06T12:34:16+0000 NXluxiBisu [info] getUpdateServerResponse response: Array
(
    [version] => 16.0.5.1
    [versionstring] => Nextcloud 16.0.5
    [url] => https://download.nextcloud.com/server/releases/nextcloud-16.0.5.zip
    [web] => https://docs.nextcloud.com/server/16/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=16.0.5
    [autoupdater] => 1
    [eol] => 0
    [signature] => iAsxJoaWRQ/1A0M3PuiDehji4x0Ci158wpa5IAv+oZbuWdhOqZjcZbLf/2cWWeCL
ggZX8WJpdJw8ZDKNtInVpfcbI558mu0L9axjl7Cpl9T8lvF9uXOa26tgeuVV5Zh0
TKlB2rdZESjvMgCNgK7WgsYqCwspvnUsRRthssuSHA0mLCJuFDr73FiDi4fQPBlr
UuRojwQ1uHlNgct/cBElCwqCWkX4mx4CRC0jQh7jV/rdF4Cy0+ajWXMOBJgkyDkG
CLEAXZOCRmDQGFJT30TACL+cVYTrhMHGsha8I4v5/LOQhYQRaDLVqHPbrvJ2ge1N
ZGWQu68eon7Vfr0iKKPJ3A==
)

2019-11-06T12:34:16+0000 NXluxiBisu [info] storage location: /nextcloud-data/updater-ocy8vdbaooo6/downloads/
2019-11-06T12:34:17+0000 NXluxiBisu [info] end of verifyIntegrity()
2019-11-06T12:34:17+0000 NXluxiBisu [info] endStep("5")
2019-11-06T12:34:17+0000 sVNGZzUrHu [info] request to updater
2019-11-06T12:34:17+0000 sVNGZzUrHu [info] currentStep()
2019-11-06T12:34:17+0000 sVNGZzUrHu [info] Step 5 is in state "end".
2019-11-06T12:34:17+0000 sVNGZzUrHu [info] POST request for step "6"
2019-11-06T12:34:17+0000 sVNGZzUrHu [info] startStep("6")
2019-11-06T12:34:17+0000 sVNGZzUrHu [info] extractDownload()
2019-11-06T12:34:17+0000 sVNGZzUrHu [info] storage location: /nextcloud-data/updater-ocy8vdbaooo6/downloads/
2019-11-06T12:34:20+0000 sVNGZzUrHu [info] end of extractDownload()
2019-11-06T12:34:20+0000 sVNGZzUrHu [info] endStep("6")
2019-11-06T12:34:20+0000 g2NQTfN3zY [info] request to updater
2019-11-06T12:34:20+0000 g2NQTfN3zY [info] currentStep()
2019-11-06T12:34:20+0000 g2NQTfN3zY [info] Step 6 is in state "end".
2019-11-06T12:34:20+0000 g2NQTfN3zY [info] POST request for step "7"
2019-11-06T12:34:20+0000 g2NQTfN3zY [info] startStep("7")
2019-11-06T12:34:20+0000 g2NQTfN3zY [info] setMaintenanceMode("true")
2019-11-06T12:34:20+0000 g2NQTfN3zY [info] configFileName /var/www/html/updater/../config/config.php
2019-11-06T12:34:20+0000 g2NQTfN3zY [info] end of setMaintenanceMode()
2019-11-06T12:34:20+0000 g2NQTfN3zY [info] endStep("7")
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] request to updater
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] currentStep()
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] Step 7 is in state "end".
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] POST request for step "8"
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] startStep("8")
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] replaceEntryPoints()
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] replace index.php
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] replace status.php
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] replace remote.php
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] replace public.php
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] replace ocs/v1.php
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] replace ocs/v2.php
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] end of replaceEntryPoints()
2019-11-06T12:34:20+0000 HwQASq5PI0 [info] endStep("8")
2019-11-06T12:34:20+0000 v8TouFb7yi [info] request to updater
2019-11-06T12:34:20+0000 v8TouFb7yi [info] currentStep()
2019-11-06T12:34:20+0000 v8TouFb7yi [info] Step 8 is in state "end".
2019-11-06T12:34:20+0000 v8TouFb7yi [info] POST request for step "9"
2019-11-06T12:34:20+0000 v8TouFb7yi [info] startStep("9")
2019-11-06T12:34:20+0000 v8TouFb7yi [info] deleteOldFiles()
2019-11-06T12:34:20+0000 v8TouFb7yi [info] config sample exists
2019-11-06T12:34:20+0000 v8TouFb7yi [info] themes README exists
2019-11-06T12:34:20+0000 v8TouFb7yi [error] POST request failed with other exception
2019-11-06T12:34:20+0000 v8TouFb7yi [error] Exception: Exception
Message: Could not rmdir: /var/www/html/updater/../lib
Code:0
Trace:
#0 /var/www/html/updater/index.php(1337): Updater->deleteOldFiles()
#1 {main}
File:/var/www/html/updater/index.php
Line:964

2019-11-06T12:34:20+0000 v8TouFb7yi [info] rollbackChanges("9")
2019-11-06T12:34:20+0000 v8TouFb7yi [info] unlink .step
2019-11-06T12:34:20+0000 v8TouFb7yi [info] rollbackChanges - step >= 7
2019-11-06T12:34:20+0000 v8TouFb7yi [info] end of  rollbackChanges()
2019-11-06T12:42:23+0000 JU4ZV3PKKl [info] request to updater
2019-11-06T12:42:23+0000 JU4ZV3PKKl [info] currentStep()
2019-11-06T12:42:23+0000 JU4ZV3PKKl [info] POST request for step "9"
2019-11-06T12:42:23+0000 JU4ZV3PKKl [info] startStep("9")
2019-11-06T12:42:23+0000 JU4ZV3PKKl [info] deleteOldFiles()
2019-11-06T12:42:23+0000 JU4ZV3PKKl [error] POST request failed with other exception
2019-11-06T12:42:23+0000 JU4ZV3PKKl [error] Exception: Exception
Message: Could not rmdir: /var/www/html/updater/../lib
Code:0
Trace:
#0 /var/www/html/updater/index.php(1337): Updater->deleteOldFiles()
#1 {main}
File:/var/www/html/updater/index.php
Line:964

2019-11-06T12:42:23+0000 JU4ZV3PKKl [info] rollbackChanges("9")
2019-11-06T12:42:23+0000 JU4ZV3PKKl [info] unlink .step
2019-11-06T12:42:23+0000 JU4ZV3PKKl [info] rollbackChanges - step >= 7
2019-11-06T12:42:23+0000 JU4ZV3PKKl [info] end of  rollbackChanges()
2019-11-06T12:42:24+0000 7enYEt8RH8 [info] request to updater
2019-11-06T12:42:24+0000 7enYEt8RH8 [info] currentStep()
2019-11-06T12:42:24+0000 7enYEt8RH8 [info] POST request for step "9"
2019-11-06T12:42:25+0000 7enYEt8RH8 [info] startStep("9")
2019-11-06T12:42:25+0000 7enYEt8RH8 [info] deleteOldFiles()
2019-11-06T12:42:25+0000 7enYEt8RH8 [error] POST request failed with other exception
2019-11-06T12:42:25+0000 7enYEt8RH8 [error] Exception: Exception
Message: Could not rmdir: /var/www/html/updater/../lib
Code:0
Trace:
#0 /var/www/html/updater/index.php(1337): Updater->deleteOldFiles()
#1 {main}
File:/var/www/html/updater/index.php
Line:964

2019-11-06T12:42:25+0000 7enYEt8RH8 [info] rollbackChanges("9")
2019-11-06T12:42:25+0000 7enYEt8RH8 [info] unlink .step
2019-11-06T12:42:25+0000 7enYEt8RH8 [info] rollbackChanges - step >= 7
2019-11-06T12:42:25+0000 7enYEt8RH8 [info] end of  rollbackChanges()
2019-11-06T12:42:25+0000 CHSlmUSC8r [info] request to updater
2019-11-06T12:42:25+0000 CHSlmUSC8r [info] currentStep()
2019-11-06T12:42:25+0000 CHSlmUSC8r [info] POST request for step "9"
2019-11-06T12:42:25+0000 CHSlmUSC8r [info] startStep("9")
2019-11-06T12:42:25+0000 CHSlmUSC8r [info] deleteOldFiles()
2019-11-06T12:42:25+0000 CHSlmUSC8r [error] POST request failed with other exception
2019-11-06T12:42:25+0000 CHSlmUSC8r [error] Exception: Exception
Message: Could not rmdir: /var/www/html/updater/../lib
Code:0
Trace:
#0 /var/www/html/updater/index.php(1337): Updater->deleteOldFiles()
#1 {main}
File:/var/www/html/updater/index.php
Line:964

2019-11-06T12:42:25+0000 CHSlmUSC8r [info] rollbackChanges("9")
2019-11-06T12:42:25+0000 CHSlmUSC8r [info] unlink .step
2019-11-06T12:42:25+0000 CHSlmUSC8r [info] rollbackChanges - step >= 7
2019-11-06T12:42:25+0000 CHSlmUSC8r [info] end of  rollbackChanges()
2019-11-06T12:42:26+0000 tMhNHAYK7Z [info] request to updater
2019-11-06T12:42:26+0000 tMhNHAYK7Z [info] currentStep()
2019-11-06T12:42:26+0000 tMhNHAYK7Z [info] POST request for step "9"
2019-11-06T12:42:26+0000 tMhNHAYK7Z [info] startStep("9")
2019-11-06T12:42:26+0000 tMhNHAYK7Z [info] deleteOldFiles()
2019-11-06T12:42:26+0000 tMhNHAYK7Z [error] POST request failed with other exception
2019-11-06T12:42:26+0000 tMhNHAYK7Z [error] Exception: Exception
Message: Could not rmdir: /var/www/html/updater/../lib
Code:0
Trace:
#0 /var/www/html/updater/index.php(1337): Updater->deleteOldFiles()
#1 {main}
File:/var/www/html/updater/index.php
Line:964

2019-11-06T12:42:26+0000 tMhNHAYK7Z [info] rollbackChanges("9")
2019-11-06T12:42:26+0000 tMhNHAYK7Z [info] unlink .step
2019-11-06T12:42:26+0000 tMhNHAYK7Z [info] rollbackChanges - step >= 7
2019-11-06T12:42:26+0000 tMhNHAYK7Z [info] end of  rollbackChanges()
```

What is the reason, how to treat?

**Comment by marcelstoer** [comment] 2021-04-28 19:55
I think this is a duplicate of that dreaded #158 - a long standing issue.

**Comment by EddyLB** [comment] 2023-10-22 18:47
Any fix foreseen? please…

**Comment by joshtrichards** [comment] 2024-04-23 20:12
Duplicate of #158

**Closed by joshtrichards** 2024-04-23 20:13 UTC
Labels: bug, feature: deletion
