### ISSUE TITLE
Allow third party apps in "apps2" directory

### ISSUE THREAD

**Issue by schuerg** [nextcloud/updater#127] opened 2017-06-29 08:51 UTC
The [Nextcloud 12 Server Administration Manual](https://docs.nextcloud.com/server/12/admin_manual/installation/apps_management_installation.html#using-custom-app-directories) states, that the directory called `apps2` should be used for custom apps.

But the Nextcloud updater fails, if this directory exists.

> The following extra files have been found:
> apps2

Imo the updater should allow custom apps in the apps2 directory.

**Comment by xraMsamohT** [comment] 2017-07-29 14:05
Duplicate of #40

**Closed** 2017-07-30 12:10 UTC
