### ISSUE TITLE
[Bug]: Updater is not working as expected

### ISSUE THREAD

**Issue by fairking** [nextcloud/updater#419] opened 2022-06-19 11:05 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Neither web update and terminal occ update not working.

Please see the following issue description: https://help.nextcloud.com/t/updater-is-not-working-as-expected/140436

### Steps to reproduce

Try to upgrade 22.2.8 into the latest version by running the following command:
```
cd /var/www/nextcloud/
sudo -u apache php ./updater/updater.phar
```

### Expected behavior

It supposed to update the nextcloud server.

### Installation method

Manual installation

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.freedns.com",
            "192.168.0.1:8090"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.8.1",
        "overwrite.cli.url": "https:\/\/mydomain.freedns.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "GB",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "enable_previews": true,
        "preview_max_x": 320,
        "preview_max_y": 320,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\PNG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "theme": "",
        "loglevel": 3,
        "debug": false,
        "upgrade.disable-web": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - bookmarks: 10.4.0
  - breezedark: 22.3.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.1
  - circles: 22.3.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.1.1
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.20.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.13.3
  - nextcloud_announcements: 1.11.0
  - notes: 4.3.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - passwords: 2021.12.20
  - phonetrack: 0.7.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.7
  - richdocumentscode: 21.11.402
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.6
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.1
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

**Comment by fairking** [comment] 2022-06-25 11:52
![image](https://user-images.githubusercontent.com/13495631/175772379-b70bdfb2-2051-487c-88db-56d0c44c15f7.png)

**Comment by fairking** [comment] 2022-06-25 14:22
I had to upgrade it manually. Please refer to the following doc: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html

**Comment by victoraroyo** [comment] 2022-09-11 10:04
It might be that old .step file was left for some reason. You can try to move/rename the old one and retry the update?

**Comment by joshtrichards** [comment] 2024-03-12 15:27
Duplicate of #378

**Closed by joshtrichards** 2024-03-12 15:27 UTC
Labels: bug, 0. Needs triage, feature: upgrade
