### ISSUE TITLE
rmdir being invoked on non-empty dirs, resulting in failed updates

### ISSUE THREAD

**Issue by VVelox** [nextcloud/updater#391] opened 2021-10-03 05:44 UTC
```
[Sun Oct 03 00:40:37.498715 2021] [fastcgi:error] [pid 14444] [client 192.168.15.2:14362] FastCGI: server "/home/thefog/www/php5-fcgis" stderr: PHP message: PHP Warning:  rmdir(/home/thefog/www/updater/../core/l10n): Directory not empty in /home/thefog/www/updater/index.php on line 1005
```

Please note that as per the PHP docs, directories must be empty for this command to work.

https://www.php.net/manual/en/function.rmdir.php

**Comment by VVelox** [comment] 2021-10-03 06:07
Looks like there is an issue with RecursiveDirectoryIterator in that it does not always start at the top of a tree with the data returned, but starts returning data at the base of the tree first, meaning rmdir will fail 100% of the time.

**Comment by joshtrichards** [comment] 2023-11-16 22:47
Duplicate of #158 

Let's consolidate this matter there.

**Closed by joshtrichards** 2023-11-16 22:47 UTC
Labels: bug, 0. Needs triage, feature: deletion
